version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ECO6hQ620ubQ
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    container_name: sql
    restart: always
